### ISSUE TITLE
使用2.2分支时遇到一个错误

### ISSUE THREAD

**Issue by zhenbeiju** [RuanShan/spree_alipay#13]
你好，
  我的是普通的2.2的spree分支，只引用了您的工程，在支付中遇到这样的报错，
  
   是不是因为我没有配置账号、密码等信息？
   这些信息写在哪里？怎么写？
  
   新手,见谅，
    谢谢！
```
NameError in Spree::CheckoutController#update
uninitialized constant ActiveMerchant::Billing::Integrations::Alipay

Rails.root: /Users/linzhang/RubymineProjects/spree/sandbox

Application Trace | Framework Trace | Full Trace
/Users/linzhang/RubymineProjects/spree_alipay/app/controllers/spree/checkout_controller_decorator.rb:155:in `handle_billing_integration'
/Users/linzhang/RubymineProjects/spree_alipay/app/controllers/spree/checkout_controller_decorator.rb:89:in `checkout_hook'
activesupport (4.0.13) lib/active_support/callbacks.rb:577:in `_run__1151578893585905700__process_action__callbacks'
```

**Comment by zhenbeiju** [comment]
在gemfile中添加了 
```
gem 'activemerchant', :require => 'active_merchant'
gem 'activemerchant_patch_for_china', github: 'RuanShan/activemerchant_patch_for_china' #support alipay
```
解决上面的问题，但是遇到新的问题
```
TypeError in Spree::CheckoutController#update
no implicit conversion of nil into String

Rails.root: /Users/linzhang/RubymineProjects/spree/sandbox

Application Trace | Framework Trace | Full Trace
/Users/linzhang/.rvm/gems/ruby-2.1.5/bundler/gems/activemerchant_patch_for_china-7559e04bc304/lib/active_merchant/billing/integrations/alipay/helper.rb:78:in `+'
/Users/linzhang/.rvm/gems/ruby-2.1.5/bundler/gems/activemerchant_patch_for_china-7559e04bc304/lib/active_merchant/billing/integrations/alipay/helper.rb:78:in `sign'
/Users/linzhang/RubymineProjects/spree_alipay/app/controllers/spree/checkout_controller_decorator.rb:131:in `aplipay_full_service_url'
/Users/linzhang/RubymineProjects/spree_alipay/app/controllers/spree/checkout_controller_decorator.rb:160:in `handle_billing_integration'
```
没有找到在哪里配置 alipay 的卖家信息

**Comment by zhenbeiju** [comment]
注释掉下面几行后可以正常跳转到淘宝，但是拼接的url出错了
```
        # alipay_helper_klass = ActiveMerchant::Billing::Integrations::Alipay::Helper
        # alipay_helper_klass.send(:remove_const, :KEY) if alipay_helper_klass.const_defined?(:KEY)
        # alipay_helper_klass.const_set(:KEY, payment_method.preferred_sign)
```

**Comment by qinghe** [comment]
@zhenbeiju   
在管理界面里添加支付方式， 配置 Partner, Sign 和 Email. 再试试，有问题联系我。

**Comment by zhenbeiju** [comment]
支付方式已经添加了， 
这是我配置的 partner，Sign，和Email，这个应该没问题吧，
在 config/enveronment.rb 中，
```
ActiveMerchant::Billing::Integrations::Alipay::Helper::KEY="**************"
ActiveMerchant::Billing::Integrations::Alipay::Helper::ACCOUNT="****"
ActiveMerchant::Billing::Integrations::Alipay::Helper::EMAIL="****.com"
```

**Comment by qinghe** [comment]
@zhenbeiju   **管理界面** 里添加支付方式,  your_site/admin  下，不是修改environment.rb文件。

**Comment by zhenbeiju** [comment]
不是的， 这是个新的错误，支付方式已经是支付宝了，跳到支付的链接出了问题，可能是少了参数，我没有仔细检查

**Comment by qinghe** [comment]
@zhenbeiju  
1. 我无法确定你出现了什么问题。
2. gemfile 参考
https://github.com/RuanShan/spree-alipay-sample/tree/2-2-stable
3. http://spree-alipay-sample-220.herokuapp.com   这个示例是好用的。

**Comment by zhenbeiju** [comment]
恩，谢谢，我再找找原因，
2015年1月22日 下午4:20于 "qing he" <notifications@github.com>写道：
